@echo off
CHCP 65001
mkdir "..\disasm\data\scripting\text\output\"
.\xdelta3_x86_64_win.exe -f -v -d -s "..\disasm\data\scripting\text\huffmantreeoffsets.bin" ".\vcdiff\huffmantreeoffsets.bin.vcdiff" "..\disasm\data\scripting\text\output\huffmantreeoffsets.bin"
.\xdelta3_x86_64_win.exe -f -v -d -s "..\disasm\data\scripting\text\huffmantrees.bin" ".\vcdiff\huffmantrees.bin.vcdiff" "..\disasm\data\scripting\text\output\huffmantrees.bin"
.\xdelta3_x86_64_win.exe -f -v -d -s "..\disasm\data\scripting\text\textbank00.bin" ".\vcdiff\textbank00.bin.vcdiff" "..\disasm\data\scripting\text\output\textbank00.bin"
.\xdelta3_x86_64_win.exe -f -v -d -s "..\disasm\data\scripting\text\textbank01.bin" ".\vcdiff\textbank01.bin.vcdiff" "..\disasm\data\scripting\text\output\textbank01.bin"
.\xdelta3_x86_64_win.exe -f -v -d -s "..\disasm\data\scripting\text\textbank02.bin" ".\vcdiff\textbank02.bin.vcdiff" "..\disasm\data\scripting\text\output\textbank02.bin"
.\xdelta3_x86_64_win.exe -f -v -d -s "..\disasm\data\scripting\text\textbank03.bin" ".\vcdiff\textbank03.bin.vcdiff" "..\disasm\data\scripting\text\output\textbank03.bin"
.\xdelta3_x86_64_win.exe -f -v -d -s "..\disasm\data\scripting\text\textbank04.bin" ".\vcdiff\textbank04.bin.vcdiff" "..\disasm\data\scripting\text\output\textbank04.bin"
.\xdelta3_x86_64_win.exe -f -v -d -s "..\disasm\data\scripting\text\textbank05.bin" ".\vcdiff\textbank05.bin.vcdiff" "..\disasm\data\scripting\text\output\textbank05.bin"
.\xdelta3_x86_64_win.exe -f -v -d -s "..\disasm\data\scripting\text\textbank06.bin" ".\vcdiff\textbank06.bin.vcdiff" "..\disasm\data\scripting\text\output\textbank06.bin"
.\xdelta3_x86_64_win.exe -f -v -d -s "..\disasm\data\scripting\text\textbank07.bin" ".\vcdiff\textbank07.bin.vcdiff" "..\disasm\data\scripting\text\output\textbank07.bin"
.\xdelta3_x86_64_win.exe -f -v -d -s "..\disasm\data\scripting\text\textbank08.bin" ".\vcdiff\textbank08.bin.vcdiff" "..\disasm\data\scripting\text\output\textbank08.bin"
.\xdelta3_x86_64_win.exe -f -v -d -s "..\disasm\data\scripting\text\textbank09.bin" ".\vcdiff\textbank09.bin.vcdiff" "..\disasm\data\scripting\text\output\textbank09.bin"
.\xdelta3_x86_64_win.exe -f -v -d -s "..\disasm\data\scripting\text\textbank10.bin" ".\vcdiff\textbank10.bin.vcdiff" "..\disasm\data\scripting\text\output\textbank10.bin"
.\xdelta3_x86_64_win.exe -f -v -d -s "..\disasm\data\scripting\text\textbank11.bin" ".\vcdiff\textbank11.bin.vcdiff" "..\disasm\data\scripting\text\output\textbank11.bin"
.\xdelta3_x86_64_win.exe -f -v -d -s "..\disasm\data\scripting\text\textbank12.bin" ".\vcdiff\textbank12.bin.vcdiff" "..\disasm\data\scripting\text\output\textbank12.bin"
.\xdelta3_x86_64_win.exe -f -v -d -s "..\disasm\data\scripting\text\textbank13.bin" ".\vcdiff\textbank13.bin.vcdiff" "..\disasm\data\scripting\text\output\textbank13.bin"
.\xdelta3_x86_64_win.exe -f -v -d -s "..\disasm\data\scripting\text\textbank14.bin" ".\vcdiff\textbank14.bin.vcdiff" "..\disasm\data\scripting\text\output\textbank14.bin"
.\xdelta3_x86_64_win.exe -f -v -d -s "..\disasm\data\scripting\text\textbank15.bin" ".\vcdiff\textbank15.bin.vcdiff" "..\disasm\data\scripting\text\output\textbank15.bin"
.\xdelta3_x86_64_win.exe -f -v -d -s "..\disasm\data\scripting\text\textbank16.bin" ".\vcdiff\textbank16.bin.vcdiff" "..\disasm\data\scripting\text\output\textbank16.bin"
move "..\disasm\data\scripting\text\output\huffmantreeoffsets.bin" "..\disasm\data\scripting\text\huffmantreeoffsets.bin"
move "..\disasm\data\scripting\text\output\huffmantrees.bin" "..\disasm\data\scripting\text\huffmantrees.bin"
move "..\disasm\data\scripting\text\output\textbank00.bin" "..\disasm\data\scripting\text\textbank00.bin"
move "..\disasm\data\scripting\text\output\textbank01.bin" "..\disasm\data\scripting\text\textbank01.bin"
move "..\disasm\data\scripting\text\output\textbank02.bin" "..\disasm\data\scripting\text\textbank02.bin"
move "..\disasm\data\scripting\text\output\textbank03.bin" "..\disasm\data\scripting\text\textbank03.bin"
move "..\disasm\data\scripting\text\output\textbank04.bin" "..\disasm\data\scripting\text\textbank04.bin"
move "..\disasm\data\scripting\text\output\textbank05.bin" "..\disasm\data\scripting\text\textbank05.bin"
move "..\disasm\data\scripting\text\output\textbank06.bin" "..\disasm\data\scripting\text\textbank06.bin"
move "..\disasm\data\scripting\text\output\textbank07.bin" "..\disasm\data\scripting\text\textbank07.bin"
move "..\disasm\data\scripting\text\output\textbank08.bin" "..\disasm\data\scripting\text\textbank08.bin"
move "..\disasm\data\scripting\text\output\textbank09.bin" "..\disasm\data\scripting\text\textbank09.bin"
move "..\disasm\data\scripting\text\output\textbank10.bin" "..\disasm\data\scripting\text\textbank10.bin"
move "..\disasm\data\scripting\text\output\textbank11.bin" "..\disasm\data\scripting\text\textbank11.bin"
move "..\disasm\data\scripting\text\output\textbank12.bin" "..\disasm\data\scripting\text\textbank12.bin"
move "..\disasm\data\scripting\text\output\textbank13.bin" "..\disasm\data\scripting\text\textbank13.bin"
move "..\disasm\data\scripting\text\output\textbank14.bin" "..\disasm\data\scripting\text\textbank14.bin"
move "..\disasm\data\scripting\text\output\textbank15.bin" "..\disasm\data\scripting\text\textbank15.bin"
move "..\disasm\data\scripting\text\output\textbank16.bin" "..\disasm\data\scripting\text\textbank16.bin"
rmdir "..\disasm\data\scripting\text\output\"